### ISSUE TITLE
Ownership

### ISSUE THREAD

**Issue by estebistec** [morepath/more.accept#1]
This repository was created a ways back when I had done some experiments around this. Clearly I haven't progressed with this, so feel free to shift this as you see fit (delete, place a new owner, etc.) I'm not using this in my day job and I didn't end up using it in the side project I was evaluating it for, so I don't want to block someone who might have ideas about this (and perhaps is using it more routinely).

**Comment by patrickbucher** [comment]
It would be nice if somebody could at least initialize the repo properly due to an [issue](https://stackoverflow.com/q/38169166) with the Ansible git module.

**Comment by jugmac00** [comment]
Sure, I could do that.

Do you plan to work on this repository?

Otherwise I could just delete it.

Hm, could you elaborate a bit why you try to clone an empty repository with Ansible? (maybe I just need more coffee :-) )

**Comment by patrickbucher** [comment]
Our organisation uses morepath, and therefore we run an automatic backup on all the public repos. I filed a [bug for Ansible](https://github.com/ansible/ansible/issues/73174) (referring to an empty repo on my account).

I do not plan to work on the repository, but our automatic backup job fails currently due to this bug. So deleting the repo would be fine for me, too.

**Comment by jugmac00** [comment]
Thanks for your feedback!

Going to archive the repository (after I have initialized it).
